version: "3.9"
services:
  coredns:
    container_name: coredns
    image: coredns/coredns
    restart: unless-stopped
    command: -conf /etc/coredns/Corefile
    ports:
      - "8.8.8.8:53:53/tcp"
      - "8.8.8.8:53:53/udp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./hosts:/etc/hosts
